import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { CustomFooter, CustomHeader, CustomSider } from "./components";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="w-screen min-h-screen flex">
          <CustomSider />
          <main className="w-[80%]">
            <CustomHeader />
            {children}
            <CustomFooter />
          </main>
        </main>
      </body>
    </html>
  );
}
